blank_issues_enabled: false
contact_links:
    - name: Feature Request
      url: https://github.com/darbotlm/dew-code/issues/new/choose
      about: Share and vote on feature requests for Dew-Coder
    - name: Leave a Review
      url: https://github.com/darbotlm/dew-code/issues
      about: Share feedback for Dew-Coder
